import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import Menu from "@/Components/Menu";

import { Metal_Mania } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NPL: GNOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-full bg-yellow-400">
        <Header />
        <div className="grow flex items-center p-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
